// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Transaction struct {
	IDTransaction  int64     `json:"id_transaction"`
	IDUser         int64     `json:"id_user"`
	TransactionsAt time.Time `json:"transactions_at"`
	TotalValue     int64     `json:"total_value"`
	Category       string    `json:"category"`
	Description    string    `json:"description"`
	IsExpense      bool      `json:"is_expense"`
}

type TransactionDetail struct {
	IDTransactionDetail int64          `json:"id_transaction_detail"`
	IDTransaction       int64          `json:"id_transaction"`
	Description         sql.NullString `json:"description"`
	Quantity            sql.NullInt32  `json:"quantity"`
	UnitValue           sql.NullInt64  `json:"unit_value"`
	TransactionDetailAt time.Time      `json:"transaction_detail_at"`
}

type User struct {
	IDUser         int64     `json:"id_user"`
	UserName       string    `json:"user_name"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	CreateAt       time.Time `json:"create_at"`
}
